AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetOUFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Role: "arn:aws:iam::831789486221:role/msingh-lambda-execute-role"
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /orgunits/{ou_urn}
            Method: get
            RestApiId: !Ref UdpTestApi 
  UdpTestApi: 
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://msingh-code/udp-swagger.yaml
    